project/annotator/forms.py
# -*- coding: utf-8 -*-
"""
Forms
******

*Module* ``project.annotator.forms``


This module defines forms used inside of the Annotator-System.

"""

from flask_wtf import FlaskForm
from wtforms import RadioField, PasswordField, StringField
from wtforms.validators import InputRequired
from ..validators import NotEqualTo, InputValid
from ..models import Annotator


class TupleForm(FlaskForm):
	"""
	Extend :fform:`FlaskForm <flask_wtf.FlaskForm>`.
	Define form for a tuple with two choices for **best** and **worst** item.

	Attributes:
		best_item (:field:`RadioField <wtforms.fields.RadioField>`): answer for the question
																	of best item
		worst_item (:field:`RadioField <wtforms.fields.RadioField>`): answer for the question
																	of worst item


	"""
	best_item = RadioField('Label', coerce=int, 
					validators= [InputRequired(message=u'Choose one item!'), \
								NotEqualTo('worst_item', 
								message=u'Two questions for this tuple require 2 different answers')
								])
	worst_item = RadioField('Label', coerce=int, 
					validators= [InputRequired(message=u'Choose one item!'),
								NotEqualTo('best_item', 
								message=u'Two questions for this tuple require 2 different answers')
								])


class AnnoCheckinForm(FlaskForm):
	"""
	Extend :fform:`FlaskForm <flask_wtf.FlaskForm>`. Define form for an annotator login-system.

	Attributes:
		keyword (:field:`PasswordField <wtforms.fields.PasswordField>`): keyword to log in
		name (:field:`StringField <wtforms.fields.StringField>`): pseudoname given by annotator

	"""
	keyword = PasswordField('Keyword as annotator', 
							validators=[InputRequired(message=u''), 
										InputValid(model=Annotator, field=Annotator.keyword, 
											message=u'Invalid keyword!')
										])
	name = StringField('Specify your name', validators=[InputRequired(message=u'')])

	
	def validate(self):
		"""
		Override  :form:`validate() <wtforms.form.Form.validate>`.

		Check if the person using this keyword is the first one who logged in
		by checking his given (pseudo)name.
		"""
		if not FlaskForm.validate(self):
			return False

		if Annotator.query.filter(Annotator.keyword==self.keyword.data, Annotator.name.isnot(None), Annotator.name==self.name.data).first() \
		 or Annotator.query.filter(Annotator.keyword==self.keyword.data, Annotator.name==None).first():
			return True
		self.name.errors.append(u'This name is not used for this keyword! Have you logged in with this keyword before? If not, someone has already used it!')
		return False

project/annotator/__init__.py
# -*- coding: utf-8 -*-
"""
*Subpackage* ``project.annotator``

This subpackage defines Annotator-System for annotators to annotate datas.

Main functions:
	* Login 
	* View all batches
	* Annotate batch

Two :bp:`Blueprints <blueprints>` define two annotator systems:
	* Local: at ``/annotator``
	* With `Mechanical Turk <https://www.mturk.com/>`__: at ``/mturk``
"""

from flask import Blueprint

annotator_app = Blueprint('annotator',__name__, url_prefix='/annotator')
hit_app = Blueprint('mturk', __name__, url_prefix='/mturk')

from . import account, views, annotation

project/annotator/views.py
# -*- coding: utf-8 -*-
"""
Views
#################

*Module* ``project.annotator.views``

This module defines routes to manage views for annotators.

"""

from flask_login import login_required, current_user
from flask import render_template
from . import annotator_app
from .helpers import batches_list

# Annotator - Project page with all batches
@annotator_app.route('/<p_name>', methods=['GET'])
@login_required
def project(p_name):
	"""
	View project with all batches corresponding to given keyword at ``/annotator/<p_name>``.
	
	Args:
		p_name (str): project name
		
	Returns:
		Status of each batch in project if they are submitted by this annotator or not.
	
	"""

	# current_user in flask_login is now the current logged in annotator
	current_project = current_user.project

	# check whether this annotator has submitted this batch, if yes, this batch is no longer active.
	check_batches = []
	for batch in current_project.batches:
		if batch in current_user.batches:
			check_batches.append(True)
		else:
			check_batches.append(False)

	return render_template('annotator/project.html', 
							batches_links=batches_list(p_name, n_batches=len(current_project.batches)),
							zip=zip, check=check_batches, project=current_project)

project/templates/annotator/batch.html
{%- extends "bootstrap/base.html" %}

{% block html_attribs %} lang="en" {% endblock %}
{% block meta %} charset="UTF-8" {% endblock %}

{% block title %} 
  {% if batch_id %}
    BATCH {{batch_id}} 
  {% elif hit_id %}
    HIT {{hit_id}}
  {% endif %}
{% endblock %}

{% block navbar %}
<div class="navbar-nav-scroll" style=" padding-left: 75%;">
  <ul class="navbar-nav bd-navbar-nav flex-row" style="list-style-type:none;">
    <li class="nav-item">
      <a class="nav-link col-xs-4"  href="{{url_for('start')}}" style="font-size: 20px; color: dodgerblue"> Home </a>
      <a class="nav-link active col-xs-4"  href="{{url_for('user.main')}}" style="font-size: 20px; color: dodgerblue">  User </a>
      <a class="nav-link col-xs-4"  href="{{url_for('annotator.login')}}" style="font-size: 20px; color: dodgerblue"> <b>Annotator </b> </a>
    </li>
  </ul>
</div>
{% endblock %}

{% block content %}
<div class="col-md-12">
  <div class="alert alert-info" role="alert">
    <h3 class="alert-heading"> <strong> Project description </strong> </h3>
    <p> <em> {{ description }} </em> </p>
    <hr>
    <h3> <strong> Task-specific instructions </strong> </h3>
    <ul>
      <li> In each set (tuple), you will be given {{tuple_size}} items. You will be asked two questions:</li>
        <ol>
          <p> Question a): Choose the item which is, in your opinion, likely to be  <strong>"{{best.upper()}}".</strong></p>
          <p> Question b): Choose the item which is, in your opinion, likely to be  <strong>"{{worst.upper()}}".</strong></p>
        </ol>

      <li>You are not allowed to choose an item as both {{best}} and {{worst}} in the same tuple.</li>
      {% if not mturk %}
      <li> Your submitted data are only validated if you answer all the questions. Or you can save this batch and complete it later!</li>
      {% else %}
      <li> Your submitted data are only validated if you answer all the questions!</li>
      {% endif %}
    </ul>
  </div>

  <div class= "needs-validation col-md-12" novalidate>
    <form action="" method = "post" enctype="multipart/form-data">

      {% for question, tuple, form in zip(question_number, tuples, batch_form) %}
      <ol>
        <strong>{{question}}. Tuple {{question}}: {{tuple}} </strong>
        <br>
          <p>Question a): Choose the item which is, in your opinion, likely to be <strong>"{{best.upper()}}"</strong>:</p>
        
          <ul style="list-style-type:none">
            {% for subform in form.best_item %}
              {% if form.best_item.default and int(subform._value()) == form.best_item.default %}
              <li> {{ subform(checked="checked") }} {{ subform.label }} </li>
              {% else %}
              <li> {{ subform }} {{ subform.label }} </li>
              {% endif %}
            {% endfor %}
          </ul>
          {% for error in form.best_item.errors %}
            <p align="center"> <font color="red"> {{ error }}  </font> </p>
          {% endfor %}

          <p> Question b): Choose the item which is, in your opinion, likely to be <strong>"{{worst.upper()}}"</strong>:
          </p>

          <ul style="list-style-type:none">
            {% for subform in form.worst_item %}
              {% if form.worst_item.default and int(subform._value()) == form.worst_item.default %}
              <li> {{ subform(checked="checked") }} {{ subform.label }} </li>
              {% else %}
              <li> {{ subform }} {{ subform.label }} </li>
              {% endif %}
           
            {% endfor %}
           </ul>
          {% for error in form.worst_item.errors %}
            <p align="center"> <font color="red"> {{ error }}  </font> </p>
          {% endfor %}
        {{ form.hidden_tag() }}
          
       </ol>
      {% endfor %}

      <div class= "container">
        <div class="row">
          <div class="col-xs-12" align="center">
            {% if not mturk %}
            <button class="btn btn-danger btn-lg" name='action' value='save'> Save </button>
            {% endif %}
            
            <button type="submit" class="btn btn-success btn-lg" name='action' value='submit'> Submit </button>
            
            {% if not mturk %}
            <a href="{{ url_for('annotator.project', p_name=p_name) }}" class="btn btn-primary mb-2 btn-lg"> Cancel  </a>
            {% endif %}
          </div>  
        </div>      
      </div>
      <br>
    </form> 
  </div>
</div> 

{% endblock %}


project/templates/annotator/index.html
{%- extends "bootstrap/base.html" %}
{%- import "bootstrap/wtf.html" as wtf%}

{% block html_attribs %} lang="en" {% endblock %}
{% block meta %} charset="UTF-8" {% endblock %}

{% block title %} Annotator - Main page {% endblock %}


{% block navbar %}
<div class="navbar-nav-scroll" style=" padding-left: 75%;">
  <ul class="navbar-nav bd-navbar-nav flex-row" style="list-style-type:none;">
  	<li class="nav-item">
	  <a class="nav-link col-xs-4"  href="{{url_for('start')}}" style="font-size: 20px; color: dodgerblue"> Home </a>
	</li>

	<li class="nav-item">
	  <a class="nav-link active col-xs-4"  href="{{url_for('user.main')}}" style="font-size: 20px; color: dodgerblue">  User </a>
	</li>

	<li class="nav-item col-md-3">
	  <a class="nav-link col-xs-4"  href="{{url_for('annotator.login')}}" style="font-size: 20px; color: dodgerblue"> <b>Annotator </b> </a>
	</li>
  </ul>
</div>
{% endblock %}

{% block content %}
<div class="container" style="min-height: 100%;">
  <form class="form-signin" method="post" action="">
	<div class="bg-info col-md-12" role="info" style="padding: 10pt; padding-bottom: 10px">
	  
	  <h2 class="modal-title" > <b> Welcome to the main page! </b></h2>

	  <ul style="font-size: 14pt">
	    <li>Enter your password and your pseudoname to access the project site!</li> 
	  	<li> This pseudoname is your choice when you first log in to this site so that no one else can use this given keyword to change your annotations. </li>
	  </ul>
				  
	  <div class="form-row">  
		  <div class="form-group col-md-4" style="font-size: 12pt">{{ wtf.form_field(form.keyword, type="password", class="form-control", placeholder='keyword to project') }} </div>

		  <div class="form-group col-md-4" style="font-size: 12pt">{{ wtf.form_field(form.name, class="form-control", placeholder='your chosen (pseudo)name')}} </div>

		  {{ form.hidden_tag() }}
				  	 

		  <div class="form-group col-md-3" style="padding: 18pt"> 
		  	<button class="btn btn-primary" style="font-size: 12pt">Confirm identity</button>
		  </div>
	  </div>		  	
			
	</div>
  </form>
</div>

<footer class="page-footer font-small">
  <div class="footer-copyright text-center py-3" style="position: absolute; bottom: 0; width:100%; background: dodgerblue; height: 20px; color: white; font-size: 10pt" >
    &copy;2020, D. Nguyen, M. Charniuk, S. Safdel., Web Interface for Best-Worst-Scaling
  </div>
</footer>
{% endblock %}

project/templates/annotator/project.html
{%- extends "bootstrap/base.html" %}

{% block html_attribs %} lang="en" {% endblock %}
{% block meta %} charset="UTF-8" {% endblock %}

{% block title %} {{ project.name.upper() }} {% endblock %}

{% block navbar %}
<div class="navbar-nav-scroll" style=" padding-left: 75%;">
  <ul class="navbar-nav bd-navbar-nav flex-row" style="list-style-type:none;">
  	<li class="nav-item">
	  <a class="nav-link col-xs-4"  href="{{url_for('start')}}" style="font-size: 20px; color: dodgerblue"> Home </a>
	  <a class="nav-link active col-xs-4"  href="{{url_for('user.main')}}" style="font-size: 20px; color: dodgerblue">  User </a>
	  <a class="nav-link col-xs-4"  href="{{url_for('annotator.login')}}" style="font-size: 20px; color: dodgerblue"> <b>Annotator </b> </a>
	</li>
  </ul>
</div>
{% endblock %}

{% block content %}
<div class="col-md-12">
  <div class="alert alert-info" role="alert">
  	<h2 class="alert-heading"> <b> {{ project.name.upper() }} </b> </h2>
  	<hr>
   	<h4 class="mb-0"> <strong> Project description </strong> </h4>
   	<p> <em> {{ project.description }} </em> </p>
  	<hr>
  	<h4> Choose a batch to start your annotation! You can annotate as many batches as you want. </h4>
  </div>

  <div class="form-group col-md-12">
  	{% for (p_name, batch_id, b_name), cbatch in zip(batches_links, check) %}
	  {% if cbatch %}
	  	<button class="btn btn-info" disabled="true"> {{ b_name }} <span class="glyphicon glyphicon-ok-sign"/> </button>
	  {% else %}
	  	<a class="btn btn-default" href="{{ url_for('annotator.batch', p_name=p_name, batch_id=batch_id) }}" >{{ b_name }} <span class="glyphicon glyphicon-question-sign"/> </a>
	  {% endif %}

  	{% endfor %}

  	<p>
	  {% with messages = get_flashed_messages(category_filter=['action']) %}
	  	{% if messages %}
		  <ul class=flashes>
		  	{% for message in messages %}
			  <div aria-live="polite" role="status" data-autohide="false" aria-atomic="true" class="toast col-md-2" style="position: absolute; top: 0; right: 8%">
				  
			    <div class="toast-header">
				  <strong class="mr-auto">Admin</strong>

				  <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			  	</div>
			    <div class="toast-body">
				  <font color="red"> {{ message }} </font>
			  	</div>
				  
			  </div>
			  
		  	{% endfor %}
		  </ul>
	  	{% endif %}
	  {% endwith %}
  	</p>
  </div>
</div>

<footer>
  <div class="footer-copyright text-center"  style="position: absolute; bottom: 0; width:100%; background: dodgerblue; height: 20px; color: white; font-size: 10pt">
    &copy;2020, D. Nguyen, M. Charniuk, S. Safdel., Web Interface for Best-Worst-Scaling
  </div>
</footer>
{% endblock %}

{% block scripts %}
{{super()}}
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
{% endblock %}