project/user/forms.py
# -*- coding: utf-8 -*-
"""
Forms
******

*Module* ``project.user.forms``

This module defines forms used inside User-System.

"""

from flask_wtf import FlaskForm
from wtforms import (StringField, PasswordField, BooleanField, TextAreaField, 
			IntegerField, MultipleFileField, SelectField, FloatField)
from wtforms.validators import InputRequired, Length, Email, Optional
from ..validators import InputValid, Unique, NotEqualTo, allowed_file
from ..models import User


class LoginForm(FlaskForm):
	"""
	Extend :fform:`FlaskForm <flask_wtf.FlaskForm>`. Define login form.

	Attributes:
		username (:field:`StringField <wtforms.fields.StringField>`): username
		password (:field:`PasswordField <wtforms.fields.PasswordField>`): password of user
		remember (:field:`BooleanField <wtforms.fields.BooleanField>`): whether to remember 
																data of this account

	"""

	username = StringField(u'Username', 
							validators=[InputRequired(message=u''), Length(min=4, max=15), 
										InputValid(model=User, field=User.username, 
											message=u'Invalid username! Have you signed up?')
										])
	password = PasswordField(u'Password', 
							validators=[InputRequired(message=u''), Length(min=8, max=80)])
	remember = BooleanField(u'Remember me')

	def validate(self):
		"""
		Override :form:`validate() <wtforms.form.Form.validate>`.

		Check if given password is valid with given valid username.
		"""
		if not FlaskForm.validate(self):
			return False

		user = User.query.filter_by(username=self.username.data).first()
		if user and user.check_password(self.password.data):
			return True
		self.password.errors.append(u'Invalid password!')
		return False


class RegisterForm(FlaskForm):
	"""
	Extend :fform:`FlaskForm <flask_wtf.FlaskForm>`. Define registration form.

	Attributes:
		username (:field:`StringField <wtforms.fields.StringField>`): username
		email (:field:`StringField <wtforms.fields.StringField>`): user email
		password (:field:`PasswordField <wtforms.fields.PasswordField>`): user password

	"""
	username = StringField(u'Username',
				validators=[InputRequired(message=u''), 
							Length(min=4, max=15, 
							 	message=u'Username must be between 4 and 15 characters long.'), 
							Unique(model=User, field=User.username, 
								message=u'Username already exists! You can log in')
							])
	email = StringField(u'Email', 
				validators=[InputRequired(message=u''), Email(message=u'Invalid email'), 
							Length(max=50), 
							Unique(model=User, field=User.email, 
								message=u'Email already exists! Use another email if you want to be a new user')
							])
	password = PasswordField(u'Password', 
				validators=[InputRequired(message=u''), 
							Length(min=8, max=80, 
								message=u'Password must be between 8 and 80 characters long.')
							])

	def validate_username(form, self):
		"""
		Validate :attr:`username`. 

		Username is not allowed to have space or special character.
		"""
		if not self.data.isalnum():
			self.errors.append(u'Username is not allowed to have space or special characters!')
			return False
		return True


class ProjectInformationForm(FlaskForm):
	"""
	Extend :fform:`FlaskForm <flask_wtf.FlaskForm>`. Define form to upload a project.

	Attributes:
		upload (:field:`MultipleFileField <wtforms.fields.MultipleFileField>`): files of items
		name (:field:`StringField <wtforms.fields.StringField>`): project name
		description (:field:`TextAreaField <wtforms.fields.TextAreaField>`): project description
		anno_number (:field:`IntegerField <wtforms.fields.IntegerField>`): number of expected annotators 
																			for this project
		best_def (:field:`StringField <wtforms.fields.StringField>`): Definition of '**best**' 
																	in this project
		worst_def (:field:`StringField <wtforms.fields.StringField>`): Definition of '**worst**' 
																	in this project
		mturk (:field:`BooleanField <wtforms.fields.BooleanField>`): Whether to upload this project 
																	on Mechanical Turk
		aws_access_key_id (:field:`StringField <wtforms.fields.StringField>`, optional): IAM AWS access key id, 
																*only provide if set* :attr:`mturk` == ``True``
		aws_secret_access_key (:field:`StringField <wtforms.fields.StringField>`, optional): IAM AWS secret access key, 
																*only provide if set* :attr:`mturk` == ``True`` 
		keywords (:field:`StringField <wtforms.fields.StringField>`, optional): keywords to describe the project 
																on Mechanical Turk, *default:* ``e.g. quick, sentiment, labeling``, 
																*only provide if set* :attr:`mturk` == ``True``
		reward (:field:`StringField <wtforms.fields.StringField>`, optional): reward for an annotator/turker 
																to annotate a HIT, *default:* ``0.15``, 
																*only provide if set* :attr:`mturk` == ``True``
		lifetime (:field:`IntegerField <wtforms.fields.IntegerField>`, optional): duration of the project 
																to be availabe on Mechanical Turk, *default:* ``1``,
																*only provide if set* :attr:`mturk` == ``True``
		lifetimeunit (:field:`SelectField <wtforms.fields.SelectField>`, optional): duration unit for :attr:`lifetime`, 
																*default:* ``month``, 
																*only provide if set* :attr:`mturk` == ``True``
		hit_duration (:field:`IntegerField <wtforms.fields.IntegerField>`, optional): duration of a HIT annotation 
																for each annotator, *default:* ``1``, 
																*only provide if set* :attr:`mturk` == ``True``
		duration_unit (:field:`SelectField <wtforms.fields.SelectField>`, optional): duration unit for :attr:`hit_duration`, 
																*default:* ``month``, 
																*only provide if set* :attr:`mturk` == ``True``

	"""
	upload = MultipleFileField(u'Upload file(s) of items (.txt)', validators=[InputRequired(message=u'')])
	name = StringField(u'Name of this project', validators=[Optional()])
	description = TextAreaField(u'Description of this project (min. 20 characters)', 
					validators=[InputRequired(message=u''), Length(min=20)] )
	anno_number = IntegerField(u'Number of expected annotators for this project', 
					validators=[InputRequired(message=u'')])
	best_def = StringField(u"What does 'best' literally mean in this project?", 
							validators=[InputRequired(message=u''), 
										NotEqualTo('worst_def', 
											message=u'Both definitions are not the same!')
										])
	worst_def = StringField(u"What does 'worst' literally mean in this project?", 
							validators=[InputRequired(message=u''), 
										NotEqualTo('best_def', 
											message=u'Both definitions are not the same!')
										])
	mturk = BooleanField(u'Upload project on Mechanical Turk Platform?', 
				validators=[Optional()], default=False)

	# optional extra values if mturk == True
	aws_access_key_id = StringField(u'Your IAM AWS access key', 
							validators=[InputRequired(u'')], default='your_aws_access_key_id')
	aws_secret_access_key = StringField(u'Your IAM AWS secret access key', 
							validators=[InputRequired(u'')], default='your_aws_secret_access_key')
	keywords = StringField(u'Keywords describing this project', 
					validators=[InputRequired(u'')], default='quick, sentiment, labeling')
	reward = StringField(u'Reward for each HIT', validators=[InputRequired(u'')], default='0.15')
	lifetime = IntegerField(u'Project lifetime', validators=[InputRequired(u'')], default=1)
	lifetimeunit = SelectField(u'In unit', 
						choices=[('m', 'month(s)'), ('d', 'day(s)'), 
								('h', 'hour(s)'), ('min', 'minute(s)')], 
						default='h',
						validators=[Optional()]
						)
	hit_duration = IntegerField(u'HIT duration', validators=[InputRequired(u'')], default=1)
	duration_unit = SelectField(u'In unit', 
						choices=[('m', 'month(s)'), ('d', 'day(s)'), 
								('h', 'hour(s)'), ('min', 'minute(s)')],
						default='h',
						validators=[Optional()]
						)
	

	def validate_upload(form, self):
		"""
		Validate uploaded files :attr:`upload`. 
		
		Check if uploaded file(s) has/have one of the allowed extensions (*default:* ``{'txt'}``).
		"""
		ALLOWED_EXTENSIONS = set(['txt'])	
		if not any([allowed_file(file.filename) for file in self.data]):
			self.errors.append(u'No %s file(s)'%(', '.join(ALLOWED_EXTENSIONS)))
			return False
		
		return True

project/user/__init__.py
# -*- coding: utf-8 -*-
"""

*Subpackage* ``project.user``

This subpackage defines User-System.

Main functions:
	* Signup-Login 
	* View profiles, projects
	* Upload projects
	* Get outputs

A :bp:`Blueprint <blueprints>` defines this user system: under ``/user``

"""

from flask import Blueprint

user_app = Blueprint('user', __name__, url_prefix='/user')

from . import account, inputs, views, outputs

project/user/views.py
# -*- coding: utf-8 -*-
"""
Views
#################

*Module* ``project.user.views``

This module defines routes to manage views for users.

"""

from flask import render_template, redirect, url_for, flash, current_app
from flask_login import login_required, logout_user, current_user
from . import user_app
from .forms import LoginForm
from .helpers import generate_keyword, is_not_current_user
from ..models import Project

# User - Homepage
@user_app.route('', methods=['GET'])
def main():
	"""
	View homepage of user system at ``/user``.
	
	"""
	return render_template('user/index.html')

# User - View profile
@user_app.route('/<some_name>', methods=['GET','POST'])
@login_required 
def profile(some_name):
	"""
	View profile of an account within user system at ``/user/<some_name>``.
	
	Args:
		some_name (str): name of the user
	
	Returns:
		Project site if account is validated.

	Note:
		Show table of all user projects.
	
	Error:
		Error message emerges if there is no logged in user.
		
	"""
	# only between users in User-System, no access to an account 
	# (not currently signed in account) without providing password
	if is_not_current_user(user=current_user, current_name=some_name):
		flash(f'Your username is "{current_user.username}", you have no access to another account without password.', 'login')
		logout_user()
		return redirect(url_for('user.login', form=LoginForm()))

	# print all projects' information of current user within his profile
	projects = { i+1:{ 'p_name':project.p_name, 'name':project.name, 
						'description': project.description[:21]+"...", 'n_anno': project.anno_number, 
						'best': project.best_def, 'worst': project.worst_def }
						for i, project in enumerate(current_user.projects) } \
				if current_user.projects else None
	other_keys = ['n_anno', 'best', 'worst', 'description']

	# define style for the titles in table of projects
	title_styles = { '': '10', 'Project':'80', 'Number of annotators':'15', 
					"Definition of 'best'":'30', "Definition of 'worst'":'30', "Description":'100' }
	if projects:
		projects = projects.items()
	return render_template('user/profile.html', name=some_name, projects=projects, 
									styles=title_styles.items(), keys=other_keys)


# User - View project
@user_app.route('/<some_name>/<p_name>', methods=['GET','POST'])
@login_required 
def project(some_name, p_name):
	"""
	View user project at ``/user/<some_name>/<p_name>``.
	
	Args:
		some_name (str): user name.
		p_name (str): project name.
	
	Returns:
		project information.

	Error:
		Error message emerges if there is no logged in user.

	"""
	# only between users in User-System, no access to an account 
	# (not currently signed in account) without providing password
	if is_not_current_user(user=current_user, current_name=some_name):
		flash(f'Your username is "{current_user.username}", you have no access to another account without password.', 'login')
		logout_user()
		return redirect(url_for('user.login', form=LoginForm()))

	current_project = Project.query.filter_by(p_name=p_name, user=current_user).first()

	# get project informations
	project_name = current_project.name
	description = current_project.description
	n_anno = current_project.anno_number
	n_items = current_project.n_items
	mturk = current_project.mturk

	# define information of annotators
	n_anno_join = n_anno_left = 0
	batch_infos = []

	# infos from MTurk as the number of annotators are now referred to 
	# the number of annotations for each HIT (batch)
	if mturk:
		for i, batch in enumerate(current_project.batches):
			check_tuple = batch.tuples[0]

			# get n_anno_join, check the number of annotators who submit this batch
			n_anno_join = len(check_tuple.datas)

			# get n_anno_left
			# how many annotators this batch still needs
			n_anno_left = n_anno - n_anno_join

			batch_infos.append((i+1, n_anno_join, n_anno_left))

	# normal infos as the number of annotators stay the same
	else:
		# get n_anno_join, check the number of annotators who submit any batch of this project
		# it does not count if they log in and only save their annotations
		for annotator in current_project.annotators:
			if annotator.batches:
				n_anno_join += 1

		# get n_anno_left
		# how many annotators this project still needs
		n_anno_left = n_anno - n_anno_join

	return render_template('user/project.html', 
							name=some_name, project_name=project_name, p_name=p_name,
							n_anno=n_anno, n_items=n_items, description=description,
							n_anno_join=n_anno_join, n_anno_left=n_anno_left, 
							batch_infos=batch_infos, mturk=mturk,
							mturk_url=current_app.config['MTURK_SHOW_UP_URL'])

project/templates/user/index.html
{%- extends "bootstrap/base.html" %}

{% block html_attribs %} lang="en" {% endblock %}
{% block meta %} charset="UTF-8" {% endblock %}

{% block title %} User - Homepage {% endblock %}

{% block navbar %}
<div class="navbar-nav-scroll" style=" padding-left: 75%;">
  <ul class="navbar-nav bd-navbar-nav flex-row" style="list-style-type:none;">
  	<li class="nav-item">
	  <a class="nav-link col-xs-4"  href="{{url_for('start')}}" style="font-size: 20px; color: green"> Home </a>
	  <a class="nav-link active col-xs-4"  href="{{url_for('user.main')}}" style="font-size: 20px; color: green"> <b> User</b> </a>
	  <a class="nav-link col-xs-4"  href="{{url_for('annotator.login')}}" style="font-size: 20px; color: green"> Annotator </a>
	</li>
  </ul>
</div>
{% endblock %}

{% block content %}
<div>
  <div class="form-group col-md-12">
	<div class="alert alert-success" role="alert">
	  <h2 class="alert-heading"><strong>Welcome to User Homepage !</strong></h2>
	  <hr>
	  <ul>
	  	<li><p class="mb-0">Sign up if you're a new user!</p></li>
	  	<li><p class="mb-0"> Or you can log in now!</p></li>
	  </ul>
	</div>
  </div>

  <div class="col-md-12" role="info" style="position: relative; min-height: 200px;">
	<p>
	  {% with messages = get_flashed_messages(category_filter=['new_user']) %}
		{% if messages %}
		  <ul class=flashes>
		  {% for message in messages %}
			<div role="alert" aria-live="assertive" aria-atomic="true" class="toast col-md-2" data-autohide="false" style="position: absolute; top: 0; right: 20%;">
			 
			  <div class="toast-header">
			    <strong class="mr-auto">Admin</strong>
			    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close"> <span aria-hidden="true">&times;</span> </button>
			  </div>
			  <div class="toast-body">
			    <font color="red"> {{ message }} </font>
			  </div>
			  
			</div>
		  {% endfor %}
		  </ul>
		{% endif %}
	  {% endwith %}
	</p>

	<div class= "container">
	 <div class="row in-line">
	  <div class="col-xs-6">
		
		<a href="{{ url_for('user.signup') }}" class="btn btn-warning btn-lg"> <span class=" glyphicon glyphicon-user"></span> Sign up </a>
		
		<a href="{{ url_for('user.login') }}" class="btn btn-success btn-lg"> <span class=" glyphicon glyphicon-log-in"></span> Login </a> 
		
	  </div>  
	 </div>	   
	</div>
  </div>

</div>

<footer>
  <div class="footer-copyright text-center"  style="position: absolute; bottom: 0; width:100%; background: green; height: 20px; color: lightgrey; font-size: 10pt">
    &copy;2020, D. Nguyen, M. Charniuk, S. Safdel., Web Interface for Best-Worst-Scaling
  </div>
</footer>
 
{% endblock %}

project/templates/user/login.html
{%- extends "bootstrap/base.html" %}
{%- import "bootstrap/wtf.html" as wtf%}

{% block html_attribs %} lang="en" {% endblock %}
{% block meta %} charset="UTF-8" {% endblock %}
{% block title %} LOGIN {% endblock %}

{% block navbar %}
<div class="navbar-nav-scroll" style=" padding-left: 75%;">
  <ul class="navbar-nav bd-navbar-nav flex-row" style="list-style-type:none;">
    <li class="nav-item">
      <a class="nav-link col-xs-4"  href="{{url_for('start')}}" style="font-size: 20px; color: green"> Home </a>
      <a class="nav-link active col-xs-4"  href="{{url_for('user.main')}}" style="font-size: 20px; color: green"> <b> User</b> </a>
      <a class="nav-link col-xs-4"  href="{{url_for('annotator.login')}}" style="font-size: 20px; color: green"> Annotator </a>
    </li>
  </ul>
</div>
<br>
<h2 ></h2>
{% endblock %}

{% block content %}
<div class="container" style="position: absolute; top: 5%; left: 8%">
  <div aria-live="polite" aria-atomic="true" > 
    
    {% with messages = get_flashed_messages(category_filter=['login']) %}
      {% if messages %}
      <ul class=flashes>      
        {% for message in messages %}
          <div class="col-sm-3">
            <div class="toast col-sm-3" role="alert" data-autohide="true" style="position: absolute; top: 16%; left: -2%;">
              <div class="toast-header">
                <strong class="mr-auto">Admin</strong>
                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close"> <span aria-hidden="true">&times;</span> </button>
              </div>

              <div class="toast-body">
               <font color="red"> {{ message }} </font>
              </div>
            </div>
          </div>
        {% endfor %}  
      
      </ul>
      {% endif %}
    {% endwith %}
  </div>

  <form class="form-signin"method="post" action="">

      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <h2 class="modal-title w-100 font-weight-bold text-center"> <b> Login </b> </h2>

          <div class="modal-body mx-3">

            <div class="md-form mb-5">
              <i class="fas fa-envelope prefix grey-text"></i>
              {{form.hidden_tag()}}

              {% if form.username.default %}
                {{ wtf.form_field(form.username, value=form.username.default) }}
              {% else %}
                {{ wtf.form_field(form.username) }}
              {% endif %}

              {{wtf.form_field(form.password)}}
            </div>

            {{wtf.form_field(form.remember)}}

            <div class="modal-footer d-flex justify-content-center">
              <button class="btn btn-success btn-lg"> <span class=" glyphicon glyphicon-log-in"/></span> Login </button>
              <a href="{{ url_for('user.signup') }}" class="btn btn-warning btn-lg"> <span class=" glyphicon glyphicon-user"></span> Sign up </a>
            </div>
          </div>
        </div>
      </div>
  </form>  
</div>

<footer>
  <div class="footer-copyright text-center"  style="position: absolute; bottom: 0; width:100%; background: green; height: 20px; color: lightgrey; font-size: 10pt">
    &copy;2020, D. Nguyen, M. Charniuk, S. Safdel., Web Interface for Best-Worst-Scaling
  </div>
</footer>

{% endblock %}

{% block scripts %}
{{super()}}
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <script type="text/javascript">
      $(document).ready(function(){
      $('.toast').toast('show');
    });
  </script>

{% endblock %}

project/templates/user/profile.html
{%- extends "bootstrap/base.html" %}

{% block html_attribs %} lang="en" {% endblock %}
{% block meta %} charset="UTF-8" {% endblock %}

{% block title %} {{name.upper()}} {% endblock %}

{% block navbar %}
<div class="navbar-nav-scroll" style=" padding-left: 75%;">
  <ul class="navbar-nav bd-navbar-nav flex-row" style="list-style-type:none;">
    <li class="nav-item">
	  <a class="nav-link col-xs-4"  href="{{url_for('start')}}" style="font-size: 20px; color: green"> Home </a>
	  <a class="nav-link active col-xs-4"  href="{{url_for('user.main')}}" style="font-size: 20px; color: green"> <b> User</b> </a>
	  <a class="nav-link col-xs-4"  href="{{url_for('annotator.login')}}" style="font-size: 20px; color: green"> Annotator </a>
	</li>
  </ul>
</div>
{% endblock %}

{% block content %}
<div class="col-md-12" >
  <div class="alert alert-success" role="alert">
	<h2 class="alert-heading">Hello, <b>{{name}} </b> !</h2>
	<hr>
	<p style="font-size: 12pt"> Below are all of your projects.</p>
  </div>

  <div class="form-group col-md-11" align="right">
	<form action = "{{ url_for('user.upload_project') }}" method = "post">
	 <button class="btn btn-danger"> <span class=" glyphicon glyphicon-tasks"> </span> Create new project </button>
	</form> 
  </div>

  <div class="form-group col-md-1" align="left">
	<form action = "{{ url_for('user.logout') }}" >
	 <button class="btn btn-primary"> <span class=" glyphicon glyphicon-log-out"> </span>  Logout </button>
	</form> 
  </div>

  <div class="form-group col-md-12" >
	<table class="table table-hover" align="center">
	  <thead>
		<tr class="bg-danger">
		  {% for t_name, width_ in styles %}
		    <th scope="col" style="width:{{ width_ }}px"> <p style="font-size:19px"> {{ t_name }} </p> </th>
		  {% endfor %}
		</tr>
	  </thead>

	  {% if projects %}
		<tbody>
		  {% for i, project in projects %}
			<tr>
			  <th scope="row"> <p style="font-size:17px"> {{ i }} </p> </th>
			  <td> <p style="font-size:17px"> <a href="{{ url_for('user.project', some_name=name, p_name=project['p_name']) }}"> <b> {{ project['name'] }} </b> </a> </p> </td>

			  {% for key in keys %}
				<td> <p style="font-size:17px"> {{ project[key] }} </p> </td>
			  {% endfor %}
			</tr>
		  {% endfor %}
		</tbody>
	  {% endif %}

	</table>
  </div>
</div>

<footer>
  <div class="footer-copyright text-center"  style="position: absolute; bottom: 0; width:100%; background: green; height: 20px; color: lightgrey; font-size: 10pt">
    &copy;2020, D. Nguyen, M. Charniuk, S. Safdel., Web Interface for Best-Worst-Scaling
  </div>
</footer>
{% endblock %}

project/templates/user/project.html
{%- extends "bootstrap/base.html" %}

{% block html_attribs %} lang="en" {% endblock %}
{% block meta %} charset="UTF-8" {% endblock %}

{% block title %} {{ project_name.upper() }}  {% endblock %}

{% block navbar %}
<div class="navbar-nav-scroll" style=" padding-left: 75%;">
  <ul class="navbar-nav bd-navbar-nav flex-row" style="list-style-type:none;">
    <li class="nav-item">
	    <a class="nav-link col-xs-4"  href="{{url_for('start')}}" style="font-size: 20px; color: green"> Home </a>
	    <a class="nav-link active col-xs-4"  href="{{url_for('user.main')}}" style="font-size: 20px; color: green"> <b> User</b> </a>
	    <a class="nav-link col-xs-4"  href="{{url_for('annotator.login')}}" style="font-size: 20px; color: green"> Annotator </a>
	  </li>
  </ul>
</div>
{% endblock %}

{% block content %}
<div class="col-md-12">
  <div class="alert alert-success" role="alert">
	<h2 class="alert-heading"> <b> {{ project_name }} </b> </h2>

	<p> <b> Description</b>: <em> {{ description }}</em> </p>
	<hr>

	<ul>
	  <li> <p>Number of items: <b> {{ n_items }} </b> </p> </li>
	  {% if mturk %}
		<li> <p>This project needs in total <b> {{ n_anno }} </b> annotation(s) for each HIT</p> </li>
		  <ul>
		  	{% for (batch_id, n_anno_join, n_anno_left) in batch_infos%}
		  	  <li> <p> <b> {{ n_anno_join }} </b> submitted batch <b> {{ batch_id }}</b>, this still needs <b> {{ n_anno_left }} </b> more </p> </li>
		  	{% endfor %}
		  </ul>
	  {% else %}
		<li> <p>This project needs in total <b> {{ n_anno }} </b> annotator(s)</p> </li>
		<li> <p> <b> {{ n_anno_join }} </b> joined this, this project still needs <b> {{ n_anno_left }} </b> annotator(s) more</p> </li>
	  {% endif %}
	</ul>
	<hr>

	<ul>
	  <li><p class="mb-0"> You can get your results including a file with scores for each item and a report about the whole annotation process at any time as long as the process starts. </p> </li>
	  {% if mturk %}
	    <li> <p class="mb-0"> Click on <strong>Mechanical Turk</strong>-Button and type the project name in search box to find your uploaded project on Mechanical Turk </p> </li>
	  {% else %}
		<li> <p class="mb-0"> Click on <strong>Keywords</strong>-Button to get the access keywords for annotators to your data survey. </p> </li>
	  {% endif %}
	</ul>
  </div>

 
  <div class= "container-fluid">
	<div class="row"> 
	  <div class="col-md-1">
		<button data-toggle="collapse" data-target="#results" role="button" aria-expanded="false" aria-controls="results" type="submit" class="btn btn-warning mb-3 btn-lg"> Results </button>
	  </div> 

	  {% if mturk %}
	  <div class="col-md-2">
		<a class="btn btn-info mb-2 btn-lg" href="{{ mturk_url }}" target="_blank" rel="noopener noreferrer"> Mechanical Turk </a>
	  </div>
	  {% else %}
	  <div class="col-md-2">
		<a class="btn btn-info mb-2 btn-lg" href="{{ url_for('user.get_keywords', some_name=name, p_name=p_name)}}" target="_blank" rel="noopener noreferrer"> Keywords </a>
	  </div>
	  {% endif %}

	  <div class="col-md-8" align="right">
		<a href="{{ url_for('user.profile', some_name=name) }}" class="btn btn-primary mb-2 btn-lg"> Back to profile  </a>
	  </div> 
	</div>

	<br>
	<div class="row">
	  <div class="col-md-10">
		<div class="collapse multi-collapse" id="results">
		  <div class="card card-body">
			<p style="padding-left:10px; font-size:17px"> <a href="{{ url_for('user.get_scores', some_name=name, p_name=p_name)}}" target="_blank" rel="noopener noreferrer"> scores.txt  </a> </p>
			<p style="padding-left:10px; font-size:17px"> <a href="{{ url_for('user.get_report', some_name=name, p_name=p_name)}}" target="_blank" rel="noopener noreferrer"> report.txt  </a></p> 
		  </div>
		</div>  
	  </div>
	</div>
  </div>
</div>

<footer>
  <div class="footer-copyright text-center"  style="position: absolute; bottom: 0; width:100%; background: green; height: 20px; color: lightgrey; font-size: 10pt">
    &copy;2020, D. Nguyen, M. Charniuk, S. Safdel., Web Interface for Best-Worst-Scaling
  </div>
</footer>
{% endblock %}